//https://projecteuler.net/problem=2

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
function fib(x) {
  var seq=[1,1],
  evens=[],
  y=0;
  while (y<x) {
    y=seq[seq.length-1]+seq[seq.length-2];
    if (y<x) {
      seq.push(y);
      if (y%2===0) evens.push(y);
    }
  }
  return evens.reduce(function(a,b){
    return a+b;
  });
}

fib(4000000);